name: Release and Deploy

run-name: Release and Deploy

on:
  push:
    branches:
      - main
      - beta

jobs:
  release:
    name: Release
    uses: DiogoAbu/workflows/.github/workflows/reusable_release.yml@main
    permissions:
      contents: write
    with:
      after_install_command: |
        yarn lint
    secrets:
      gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
      npm_token: ${{ secrets.NPM_TOKEN }}
